---
openapi: 3.0.3
info:
  title: account-processing
  version: 1.1.0-SNAPSHOT
tags:
- name: Statement Information
paths:
  /AccountProcessing/V1/Agreement/{agreementId}/OutstandingRepaymentAmount/Retrieve:
    get:
      tags:
      - Statement Information
      summary: The API is used to inquire minimum due amount and payment due date.
      description: The API is used to inquire minimum due amount and payment due date.
      operationId: retrieveOutstandingRepaymentAmount
      parameters:
      - name: fi-id
        in: header
        description: Financial Institution Identification
        required: true
        schema:
          maxLength: 37
          type: string
      - name: brand-id
        in: header
        description: Brand Identification
        schema:
          maxLength: 37
          type: string
      - name: agreementId
        in: path
        description: Agreement Id
        required: true
        schema:
          maxLength: 37
          pattern: "^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$"
          type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/RepaymentAmountResponse"
        "400":
          description: "Bad Request <br/><br/> <b>Error codes list:</b><br/><ul><li><em>HLXPNKPBR001\
            \ : Account Number is invalid, please provide valid value.</em></li></ul>"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HelixErrorDetails"
        "401":
          description: Not Authorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HelixErrorDetails"
        "403":
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HelixErrorDetails"
        "404":
          description: Not Found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HelixErrorDetails"
        "415":
          description: Unsupported Media Type
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HelixErrorDetails"
        "422":
          description: Unprocessable Entity
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HelixErrorDetails"
        "429":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HelixErrorDetails"
        "500":
          description: "Internal Server Error <br/><br/> <b>Error codes list:</b><br/><ul><li><em>HLXPNKPGT001\
            \ : Error Retrieving the Account Repayment Details.</em></li></ul>"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HelixErrorDetails"
        "502":
          description: Bad Gateway
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HelixErrorDetails"
        "503":
          description: Service Unavailable
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HelixErrorDetails"
        "504":
          description: Gateway Timeout
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HelixErrorDetails"
      x-proxy-name: Inquire payment due amount and payment due date
      x-group-name: Statement Information
components:
  schemas:
    AmountDto:
      type: object
      properties:
        Value:
          type: string
        Currency:
          type: string
    HelixErrorDetails:
      type: object
      properties:
        messages:
          type: array
          items:
            $ref: "#/components/schemas/HelixMessage"
    HelixMessage:
      type: object
      properties:
        errorCode:
          type: string
        type:
          type: string
        title:
          type: string
        detail:
          type: string
        instance:
          type: string
    RepaymentAmountResponse:
      type: object
      properties:
        AgreementId:
          description: Agreement ID to which this repayment belongs.
          type: string
        BillingDate:
          description: "<ul><li>Account billing date.</li><li>DueAmount: Calculated\
            \ due amount on a particular billing date on which this position type\
            \ belongs.</li></ul>"
          type: string
        PaymentDueDate:
          description: Calculated payment due date.
          type: string
        CurrentDueAmount:
          description: Calculated due amount.
          type: object
          allOf:
          - $ref: "#/components/schemas/AmountDto"
        TotalDueAmount:
          description: Current due plus past due amount.
          type: object
          allOf:
          - $ref: "#/components/schemas/AmountDto"
