---
openapi: 3.0.3
info:
  title: event-catalog
  version: 1.0.0
paths:
  /card_auth_data_ready:
    head:
      summary: A new physical card has been added. The event content will indicate details of the card, the domain it has been added it, and relevant details relating to the circumstances under which the card was added, e.g. brand new card, replacement, etc.
      operationId: addCardEvent
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/AddCardEvent"
            example:
              eventName: card_authentication_data_ready
              eventDescription: New Card has been added
              serviceDomain: Issue_Device_Admin
              entityId: 657e2fbb-00f4-44a2-8fef-0106cf347722
              subEntityId: a45f601d-e53c-4928-ad7b-b00b9b026d5d
              eventId: 3236eb36-585f-4cc7-b17c-30bd2aa7924b
              timestamp: 2023-02-09T12:21:42.947991Z
              fiId: FISERV
              brandId: HELIX
              productId: VISAPLUS
              cardholderType: PRIM
              digitalCardType: NDIG
              cardAction: NEWC
              cardTechnologyType: CLCP
              activationStatus: ANED
              feaId: ee9461c1-baa8-43f3-9c3d-5a7941621040
      responses:
        "default":
          description: Event published
      x-proxy-name: card_auth_data_ready
      x-group-name: Event Catalog
  /card_reissued:
    head:
      summary: Cards have been reissued for a product.
      operationId: getPaymentInstrumentList
      responses:
        "default":
          description: Event published
      x-proxy-name: card_reissued
      x-group-name: Event Catalog
components:
  schemas:
    AddCardEvent:
      type: object
      properties:
        eventName:
          type: string
          description: The name of the event generated
        eventDescription:
          type: string
          description: The description of the event generated
        serviceDomain:
          type: string
          description: The domain under which the event was generated
        entityId:
          type: string
          description: Token ID of the card
        subEntityId:
          type: string
          description: The Person for which the card was created (Person ID)
        eventId:
          type: string
          description: Unique identifier for the event
        timestamp:
          type: string
          description: Date and time that the event was generated
        fiId:
          type: string
          description: The Financial Institution that the card exists under
        brandId:
          type: string
          description: The Brand that the card exists under
        productId:
          type: string
          description: The Product that the card exists under
        cardholderType:
          type: string
          description: The type of cardholder added - Primary or Secondary
        digitalCardType:
          type: string
          description: Indicates whether this is a digital card or not, and if so, what type of digital card
        cardAction:
          type: string
          description: Indicates for what card action the new card was generated, e.g. new card, replacement
        cardTechnologyType:
          type: string
          description: The card technology of the card, e.g. contactless, mag stripe
        activationStatus:
          type: string
          description: The card activation status, i.e. active or inactive
        feaId:
          type: string
          description: The Account for which the card was created (Account ID)
