---
openapi: 3.0.3
info:
  title: issued-device-security
  version: 1.1.58
tags:
- name: Helix Core
paths:
  /Helix/V1/IssuedDeviceSecurity/{paymentInstrumentId}/GetCVV2/Request:
    post:
      tags:
      - Helix Core
      summary: This method is used to generate CVV2
      description: This API allows the user to generate CVV2
      operationId: generateCVV2
      parameters:
      - name: paymentInstrumentId
        in: path
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GenerateCVVRequest'
      responses:
        "200":
          description: OK
        "201":
          description: CREATED
          content:
            application/json:
              schema:
                type: object
                properties:
                  CVV:
                    description: CVV
                    type: string
                  CVV2:
                    description: CVV2
                    type: string
                  ICVV:
                    description: ICVV
                    type: string
        "400":
          description: "Bad Request <br/><br/> <b>Error codes list:</b><br/><ul><li><em>HLXDSECBR001\
            \ : FEPID required, please provide value.</em></li><li><em>HLXDSECBR001\
            \ : Expiry Date required, please provide value.</em></li><li><em>HLXDSECBR001\
            \ : Invalid Expiry Date, should be in YYMM format.</em></li></ul>"
          content: {}
        "401":
          description: Not Authorized
          content: {}
        "403":
          description: Forbidden
          content: {}
        "404":
          description: "Not Found <br/><br/> <b>Error codes list:</b><br/><ul><li><em>HLXDSECPA002\
            \ : Card does not have a PAN assigned.</em></li></ul>"
          content: {}
        "413":
          description: Payload Too large
          content: {}
        "415":
          description: Unsupported Media Type
          content: {}
        "422":
          description: Unprocessable Entity
          content: {}
        "429":
          description: Too Many Request
          content: {}
        "500":
          description: "Internal Server Error <br/><br/> <b>Error codes list:</b><br/><ul><li><em>HLXDSECCG001\
            \ : Attempt to generate CVV has failed.</em></li></ul>"
          content: {}
        "502":
          description: Bad Gateway
          content: {}
        "503":
          description: Service Unavailable
          content: {}
        "504":
          description: Gateway Timeout
          content: {}
components:
  schemas:
    GenerateCVVRequest:
      required:
      - ExpiryDate
      type: object
      properties:
        ExpiryDate:
          description: Date on which the payment instrument expires (YYMM).
          pattern: \S
          type: string
          nullable: false
        RSAPublicKey:
          description: Key used for Encrypting the data
          type: string

