---
openapi: 3.0.3
info:
  title: issued-device-admin
  version: 1.1.360
tags:
- name: Card Management
paths:
    /Helix/V1/PaymentInstrument/{paymentInstrumentId}/GetCVV2/Request:
    get:
      tags:
      - Helix Core
      summary: This method is used to generate CVV 2 the given FEPID
      description: "This API allows the user to to generate CVV2 for given FEPID <br/><br/><i>\
        \ <b>Note</b>:This API is for Internal purpose only.</i>"
      operationId: generateCVV2
      parameters:
      - name: paymentInstrumentId
        in: path
        description: Unique identifier of the payment instrument (FEPID)
        required: true
        schema:
          maxLength: 37
          type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
        "400":
          description: "Bad Request <br/><br/> <b>Error codes list:</b><br/><ul><li><em>HLXIDASBR001\
            \ : Card not found.</em></li></ul>"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HelixErrorDetails"
        "401":
          description: Not Authorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HelixErrorDetails"
        "403":
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HelixErrorDetails"
        "404":
          description: "Not Found <br/><br/> <b>Error codes list:</b><br/><ul><li><em>HLXIDASBU001\
            \ : Card not found.</em></li></ul>"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HelixErrorDetails"
        "415":
          description: Unsupported Media Type
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HelixErrorDetails"
        "429":
          description: Too Many Request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HelixErrorDetails"
        "500":
          description: "Internal Server Error <br/><br/> <b>Error codes list:</b><br/><ul><li><em>HLXIDASDP001\
            \ : Attempt to parse date has failed</em></li></ul>"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HelixErrorDetails"
        "502":
          description: Bad Gateway
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HelixErrorDetails"
        "503":
          description: Service Unavailable
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HelixErrorDetails"
        "504":
          description: Gateway Timeout
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HelixErrorDetails"
      x-proxy-name: Generate CVV2
      x-group-name: Card Management
      x-api-scope: Internal
components:
  schemas:
    GenerateCVVRequest:
      required:
      - ExpiryDate
      type: object
      properties:
        ExpiryDate:
          description: Date on which the payment instrument expires (YYMM).
          pattern: \S
          type: string
          nullable: false
        RSAPublicKey:
          description: Key used for Encrypting the data
          type: string

