---
openapi: 3.0.3
info:
  title: position-keeping
  version: 1.1.0-15
tags:
- name: Position Management
paths:
  /PositionKeeping/V1/Agreement/{agreementId}/Positions/Request:
    get:
      tags:
      - Position Management
      summary: get Position Details
      description: "TThis API is used to retrieve the positions associated with an\
        \ account. This API provides information about the balances of from financial\
        \ activities associated with the account. By utilizing optional filters for\
        \ positionType and positionComponent, users can filter the API response based\
        \ on a specific criteria. positionType allows users to narrow down the results\
        \ to a specific type of position, such as Retail (RETL) or Current (CRRT)\
        \ etc., while positionComponent enables filtering based on positionComponents\
        \ associated with a particular position, such as Principal (PRPL), Pending\
        \ (PEND) etc."
      operationId: retrievePositions
      parameters:
      - name: fi-id
        in: header
        description: Financial Institution Identification
        required: true
        schema:
          maxLength: 37
          type: string
      - name: brand-id
        in: header
        description: Brand Identification
        schema:
          maxLength: 37
          type: string
      - name: agreementId
        in: path
        description: 'The unique identifier of the account for which positions are
          to be retrieved. '
        required: true
        schema:
          maxLength: 37
          type: string
      - name: positionType
        in: query
        description: " A filter to retrieve positions of a specific type. Only positions\
          \ matching the specified position type will be returned in the response.Valid\
          \ values are: <UL><LI> RETL (Retail) </LI> <LI> CRRT (Current) </LI></UL>"
        schema:
          type: string
      - name: positionComponent
        in: query
        description: "A filter to retrieve positions associated with a specific position\
          \ component. Only positions matching the specified position component will\
          \ be returned in the response. The valid values are:<UL><LI> PRPL (Principal)\
          \ </LI><LI> PEND (Pending Balance) </LI><LI> BAL (Total Cleared Balance\
          \ for the account) </LI></UL>"
        schema:
          type: string
      - name: period
        in: query
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/RequestPositionsResponse"
        "400":
          description: "Bad Request <br/><br/> <b>Error codes list:</b><br/><ul><li><em>HLXPNKPBR001\
            \ : Account Number is required.</em></li><li><em>HLXPNKPBR001 : Account\
            \ Number is invalid, please provide valid value.</em></li><li><em>HLXPNKPBR001\
            \ : Account Number exceeds maximum 37 length allowed.</em></li></ul>"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HelixErrorDetails"
        "401":
          description: Not Authorized
          content: {}
        "403":
          description: Forbidden
          content: {}
        "413":
          description: Payload Too large
          content: {}
        "415":
          description: Unsupported Media Type
          content: {}
        "429":
          description: Too Many Request
          content: {}
        "500":
          description: "Internal Server Error <br/><br/> <b>Error codes list:</b><br/><ul><li><em>HLXPNKPGT002\
            \ : Error Retrieving the Position List.</em></li></ul>"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HelixErrorDetails"
        "502":
          description: Bad Gateway
          content: {}
        "503":
          description: Service Unavailable
          content: {}
        "504":
          description: Gateway Timeout
          content: {}
      x-proxy-name: Retrieve Positions
      x-group-name: Position Management
components:
  schemas:
    BalanceAmountDto:
      type: object
      properties:
        Amount:
          description: "Represents the monetary value associated. Precision 15, scale\
            \ 5."
          type: string
        Currency:
          description: "Represents the currency associated, expressed in ISO 4217\
            \ currency code."
          type: string
    HelixErrorDetails:
      type: object
      properties:
        messages:
          type: array
          items:
            $ref: "#/components/schemas/HelixMessage"
    HelixMessage:
      type: object
      properties:
        errorCode:
          type: string
        type:
          type: string
        title:
          type: string
        detail:
          type: string
        instance:
          type: string
    Instant:
      format: date-time
      type: string
      example: "2022-03-10T16:15:50Z"
    PositionDto:
      type: object
      properties:
        PositionID:
          description: ' A unique identifier assigned to each position for identification
            and reference purposes.'
          type: string
        Status:
          description: "Status of the Position entity in the system. Valid values\
            \ are:<UL> <LI> ENAB (Enabled) </LI></UL>"
          type: string
        CreationDateTime:
          description: "(For example, September 27, 2022 at 6 p.m. is represented\
            \ as 2022-09-27T18:00:00.000Z)<br>System Date and time when the position\
            \ was first created. Format is ISO Date and Time format (YYYY-MM-DDThh:mm:ss.sssZ)."
          type: string
          allOf:
          - $ref: "#/components/schemas/Instant"
        PositionType:
          description: "Valid values are: <UL><LI> RETL (Retail) </LI><LI> CRRT (Current)\
            \ </LI></UL> "
          type: string
        PositionComponent:
          description: "dentifies the type of position component, representing a sub-category\
            \ of balances associated with the position. The position component provides\
            \ further classification for distinguishing different types of balances\
            \ within a position, such as Principal.Valid values are: <UL><LI> PRPL\
            \ (Principal)</LI><LI> PEND (Pending Balance) </LI><LI> BAL  (Total Cleared\
            \ Balance for the account)</LI> <LI> Note: The Current (CRRT) position's,\
            \ BAL (Balance) component holds the account level cleared balance across\
            \ all the positions.</LI></UL>"
          type: string
        BalanceAmount:
          description: ' The balance amount associated with a position component.'
          type: object
          allOf:
          - $ref: "#/components/schemas/BalanceAmountDto"
    PositionEntryEvent:
      type: object
      properties:
        EventId:
          type: string
        EventName:
          type: string
        PositionID:
          type: string
        Product:
          type: string
        AgreementID:
          type: string
        PartyID:
          type: string
        CreationDateTime:
          type: string
        Amount:
          type: string
        Currency:
          type: string
        PositionType:
          type: string
        PositionComponent:
          type: string
    RequestPositionsResponse:
      type: object
      properties:
        AgreementID:
          description: Agreement ID to which this Position belongs.
          type: string
        CurrentPositions:
          description: " An array that contains a list of positions that represent\
            \ the current (cycle-to-date) balances for an account. The valid combinations\
            \ of Positions and Position Components are:<UL><LI> Position   Position\
            \ Component </LI><LI>RETL PRPL </LI><LI> RETL PEND </LI><LI> CRRT  BAL\
            \ </LI><LI>Note: The Current (CRRT) position's, BAL (Balance) component\
            \ holds the account level cleared balance across all the positions. </LI></UL>"
          type: array
          items:
            $ref: "#/components/schemas/PositionDto"
    TransactionBookingEvent:
      type: object
      properties:
        EventId:
          type: string
        EventName:
          type: string
        Product:
          type: string
        AgreementID:
          type: string
        PaymentInstrumentID:
          type: string
        PartyID:
          type: string
        Status:
          type: string
        Amount:
          type: string
        Currency:
          type: string
        EffectiveDateTime:
          type: string
        PositionType:
          type: string
        PositionComponent:
          type: string
        AuthorisationReferenceID:
          type: string
        TransactionReferenceID:
          type: string
        ClearingMatchStatusCode:
          type: string
