---
openapi: 3.0.3
info:
  title: position-keeping
  version: 1.1.0-SNAPSHOT
tags:
- name: Position Management
paths:
  /PositionKeeping/V1/Agreement/{agreementId}/Positions/Request:
    get:
      tags:
      - Position Management
      summary: get Position Details
      description: "This API is used to retrieve the positions associated with an\
        \ account. This API provides information about the balances of financial activities\
        \ associated with the account. By utilizing optional filters for positionType\
        \ and positionComponent, users can filter the API response based on a specific\
        \ criteria. positionType allows users to narrow down the results to a specific\
        \ type of position, such as Retail (RETL) or Current (CRRT) etc., while positionComponent\
        \ enables filtering based on positionComponents associated with a particular\
        \ position, such as Principal (PRPL), Pending (PEND) etc. The valid combinations\
        \ of Positions and Position Components are:<UL><LI> RETL and PRPL </LI><LI>\
        \ RETL and PEND </LI><LI> RETL and INTR </LI><LI> CASH and PRPL </LI><LI>\
        \ CASH and PEND </LI><LI> CASH and INTR </LI><LI> CRRT and BAL </LI></UL>The\
        \ filter values and filter combinations listed above are not validated by\
        \ the system, it is the responsibility of the caller to ensure that valid\
        \ filters and combinations of filters are supplied in the request parameters."
      operationId: retrievePositions
      parameters:
      - name: fi-id
        in: header
        description: Financial Institution Identification
        required: true
        schema:
          maxLength: 37
          type: string
      - name: brand-id
        in: header
        description: Brand Identification
        schema:
          maxLength: 37
          type: string
      - name: agreementId
        in: path
        description: 'The unique identifier of the account for which positions are
          to be retrieved. '
        required: true
        schema:
          pattern: "[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}"
          type: string
      - name: positionType
        in: query
        description: "A filter to retrieve positions of a specific type. Only positions\
          \ matching the specified position type will be returned in the response.\
          \ Valid values are: <UL><LI> RETL (Retail) </LI> <LI> CASH (Cash) </LI><LI>\
          \ CRRT (Current) </LI></UL>"
        schema:
          type: string
      - name: positionComponent
        in: query
        description: A filter to retrieve positions associated with a specific position
          component. Only positions matching the specified position component will
          be returned in the response. The valid values are:<UL><LI> PRPL (Principal)
          </LI><LI> PEND (Pending Balance) </LI><LI> INTR (Interest) </LI><LI> BAL
          (Total Cleared Balance for the account) </LI></UL>
        schema:
          type: string
      - name: period
        in: query
        description: A filter to retrieve position information for a specific period.
          Only positions matching the specified period will be returned in the response.
          The valid values are:<UL><LI> CURR (Current Period) </LI><LI> PRIO (Prior
          Period) </LI><LI> RESI (Residual Period) </LI></UL>
        schema:
          type: string
      responses:
        "200":
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RequestPositionsResponse'
        "400":
          description: "Bad Request <br/><br/> <b>Error codes list:</b><br/><ul><li><em>HLXPNKPBR001\
            \ : Account Number is required.</em></li><li><em>HLXPNKPBR001 : Account\
            \ Number is invalid, please provide valid value.</em></li><li><em>HLXPNKPBR001\
            \ : Account Number exceeds maximum 37 length allowed.</em></li></ul>"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HelixErrorDetails'
        "401":
          description: Not Authorized
          content: {}
        "403":
          description: Forbidden
          content: {}
        "413":
          description: Payload Too large
          content: {}
        "415":
          description: Unsupported Media Type
          content: {}
        "429":
          description: Too Many Request
          content: {}
        "500":
          description: "Internal Server Error <br/><br/> <b>Error codes list:</b><br/><ul><li><em>HLXPNKPGT002\
            \ : Error Retrieving the Position List.</em></li></ul>"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HelixErrorDetails'
        "502":
          description: Bad Gateway
          content: {}
        "503":
          description: Service Unavailable
          content: {}
        "504":
          description: Gateway Timeout
          content: {}
      x-proxy-name: Retrieve Positions
      x-group-name: Position Management
  /PositionKeeping/V1/PositionEntries/Initiate:
    post:
      tags:
      - Position Management
      summary: initiate position Entries
      description: This API is used to initiate position entries associated with an
        account.
      operationId: initiatePositionEntries
      parameters:
      - name: fi-id
        in: header
        description: Financial Institution Identification
        required: true
        schema:
          maxLength: 37
          type: string
      - name: brand-id
        in: header
        description: Brand Identification
        schema:
          maxLength: 37
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PositionEntriesInitiationRequest'
      responses:
        "201":
          description: Created
        "400":
          description: "Bad Request <br/><br/> <b>Error codes list:</b><br/><ul><li><em>HLXPNKPIN001\
            \ : Error occurred while initiating the transaction, please try again.</em></li></ul>"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HelixErrorDetails'
        "401":
          description: Not Authorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HelixErrorDetails'
        "403":
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HelixErrorDetails'
        "404":
          description: "Not Found <br/><br/> <b>Error codes list:</b><br/><ul><li><em>HLXPNKPIN001\
            \ : Error occurred while initiating the transaction, please try again.</em></li></ul>"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HelixErrorDetails'
        "415":
          description: Unsupported Media Type
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HelixErrorDetails'
        "429":
          description: Too Many Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HelixErrorDetails'
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HelixErrorDetails'
        "502":
          description: Bad Gateway
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HelixErrorDetails'
        "503":
          description: Service Unavailable
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HelixErrorDetails'
        "504":
          description: Gateway Timeout
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HelixErrorDetails'
        "200":
          description: OK
      x-proxy-name: Initiate Positions
      x-group-name: Position Entry Management
components:
  schemas:
    BalanceAmountDto:
      type: object
      properties:
        Value:
          description: "Represents the monetary value associated. Precision 15, scale\
            \ 5."
          type: string
        Currency:
          description: "Represents the currency associated, expressed in ISO 4217\
            \ currency code."
          type: string
    BillingEvent:
      type: object
      properties:
        EventId:
          type: string
        EventName:
          type: string
        AgreementId:
          type: string
        BillingDate:
          type: string
        PeriodStartDate:
          type: string
        PeriodEndDate:
          type: string
        Status:
          type: string
        NextBillingDate:
          type: string
    HelixErrorDetails:
      type: object
      properties:
        messages:
          type: array
          items:
            $ref: '#/components/schemas/HelixMessage'
    HelixMessage:
      type: object
      properties:
        errorCode:
          type: string
        type:
          type: string
        title:
          type: string
        detail:
          type: string
        instance:
          type: string
    Instant:
      format: date-time
      type: string
      example: 2022-03-10T16:15:50Z
    LocalDateTime:
      format: date-time
      type: string
      example: 2022-03-10T12:15:50
    PositionDto:
      type: object
      properties:
        PositionID:
          description: ' A unique identifier assigned to each position for identification
            and reference purposes.'
          type: string
        Status:
          description: Status of the Position entity in the system. Valid values are:<UL>
            <LI> ENAB (Enabled) </LI></UL>
          type: string
        CreationDateTime:
          description: "System Date and time when the position was first created.\
            \ Format is ISO Date and Time format (YYYY-MM-DDThh:mm:ss.sssZ). For example,\
            \ September 27, 2022 at 6 p.m is represented as 2022-09-27T18:00:00.000Z."
          type: string
          allOf:
          - $ref: '#/components/schemas/Instant'
        PositionType:
          description: "Identifies the type of position, representing a specific category\
            \ of balances associated with the account. The position type provides\
            \ a classification for grouping similar types of positions, such as Retail.\
            \ Valid values are: <UL><LI> RETL (Retail) </LI><LI> CASH (Cash) </LI><LI>\
            \ CRRT (Current) </LI></UL> "
          type: string
        PositionComponent:
          description: "Identifies the type of position component, representing a\
            \ sub-category of balances associated with the position. The position\
            \ component provides further classification for distinguishing different\
            \ types of balances within a position, such as Principal. Valid values\
            \ are: <UL><LI> PRPL (Principal)</LI><LI> PEND (Pending Balance) </LI><LI>\
            \ INTR (Interest) </LI><LI> BAL  (Total Cleared Balance for the account)</LI></UL>\
            \ Note: The Current (CRRT) position's, BAL (Balance) component holds the\
            \ account level cleared balance across all the positions."
          type: string
        BalanceAmount:
          description: The balance amount associated with a position component.
          type: object
          allOf:
          - $ref: '#/components/schemas/BalanceAmountDto'
    PositionEntriesInitiationRequest:
      type: object
      properties:
        AgreementId:
          description: Agreement ID to which these Transactions belongs.
          type: string
        PartyId:
          description: Associated Party ID to which this Transaction Belongs
          type: string
        PaymentInstrumentId:
          description: Payment Instrument ID used to perform the transaction
          type: string
        BookingType:
          description: Identification of transaction Type among Internal or External
          type: string
        PositionEntries:
          type: array
          items:
            $ref: '#/components/schemas/PositionEntry'
    PositionEntry:
      type: object
      properties:
        PositionType:
          description: "Identifies the type of position, representing a specific category\
            \ of balances associated with the account. The position type provides\
            \ a classification for grouping similar types of positions, such as Retail.\
            \ Valid values are: <UL><LI> RETL (Retail) </LI><LI> CRRT (Current) </LI></UL> "
          type: string
        PositionComponent:
          description: "Identifies the type of position component, representing a\
            \ sub-category of balances associated with the position. The position\
            \ component provides further classification for distinguishing different\
            \ types of balances within a position, such as Principal. Valid values\
            \ are: <UL><LI> PRPL (Principal)</LI><LI> PEND (Pending Balance) </LI><LI>\
            \ BAL  (Total Cleared Balance for the account)</LI></UL> Note: The Current\
            \ (CRRT) position's, BAL (Balance) component holds the account level cleared\
            \ balance across all the positions."
          type: string
        AuthorisationReferenceId:
          description: Authorisation Reference ID - Reference ID captured in Authorisation
            Domain during Authorisation Process. Mandatory for all pending transactions
            ( transactions approved but not settled) System Trace Audit Number (STAN)
            DE 11
          type: string
        TransactionReferenceId:
          description: Identification of Transaction Reference provided by transaction
            capture service.
          type: string
        EffectiveDateTime:
          description: Date when Transaction was Created
          type: string
          allOf:
          - $ref: '#/components/schemas/LocalDateTime'
        Amount:
          description: Transaction Amount
          type: object
          allOf:
          - $ref: '#/components/schemas/BalanceAmountDto'
    PositionEntryEvent:
      type: object
      properties:
        EventId:
          type: string
        EventName:
          type: string
        PositionID:
          type: string
        Product:
          type: string
        AgreementID:
          type: string
        PartyID:
          type: string
        CreationDateTime:
          type: string
        Amount:
          type: string
        Currency:
          type: string
        PositionType:
          type: string
        PositionComponent:
          type: string
        EffectiveDateTime:
          type: string
        ClearingDateTime:
          type: string
    PositionLifeCycleEvent:
      type: object
      properties:
        EventId:
          type: string
        EventName:
          type: string
        PositionId:
          type: string
        Product:
          type: string
        AgreementID:
          type: string
        PartyID:
          type: string
        Amount:
          type: string
        Currency:
          type: string
        PositionType:
          type: string
        PositionComponent:
          type: string
        EffectiveDateTime:
          type: string
        ClearingDateTime:
          type: string
    PositionRolledEvent:
      type: object
      properties:
        EventId:
          type: string
        EventName:
          type: string
        AgreementID:
          type: string
        BillingDate:
          type: string
        BillingPeriodStartDate:
          type: string
        BillingPeriodEndDate:
          type: string
    RequestPositionsResponse:
      type: object
      properties:
        AgreementID:
          description: Agreement ID to which this Position belongs.
          type: string
        CurrentPositions:
          description: "An array that contains a list of positions that represent\
            \ the current (cycle-to-date) balances for an account. The valid combinations\
            \ of Positions and Position Components are:<UL><LI>RETL and PRPL </LI><LI>\
            \ RETL and PEND </LI><LI> RETL and INTR </LI><LI> CASH and PRPL </LI><LI>\
            \ CASH and PEND </LI><LI> CASH and INTR </LI><LI> CRRT and BAL </LI></UL>Note:\
            \ The Current (CRRT) position's, BAL (Balance) component holds the account\
            \ level cleared balance across all the positions."
          type: array
          items:
            $ref: '#/components/schemas/PositionDto'
        PriorPositions:
          description: An array that contains a list of positions that represent the
            balances from the last cycle for an account. The valid combinations of
            Positions and Position Components are:<UL><LI>RETL and PRPL </LI><LI>
            RETL and PEND </LI><LI> RETL and INTR </LI><LI> CASH and PRPL </LI><LI>
            CASH and PEND </LI><LI> CASH and INTR </LI></UL>
          type: array
          items:
            $ref: '#/components/schemas/PositionDto'
        ResidualPositions:
          description: "An array that contains a list of positions that represent\
            \ the cumulative balances, that are from a period older than the last\
            \ cycle for an account. The valid combinations of Positions and Position\
            \ Components are:<UL><LI>RETL and PRPL </LI><LI> RETL and PEND </LI><LI>\
            \ RETL and INTR </LI><LI> CASH and PRPL </LI><LI> CASH and PEND </LI><LI>\
            \ CASH and INTR </LI></UL>"
          type: array
          items:
            $ref: '#/components/schemas/PositionDto'
    TransactionBookingEvent:
      type: object
      properties:
        EventId:
          type: string
        EventName:
          type: string
        Product:
          type: string
        AgreementID:
          type: string
        PaymentInstrumentID:
          type: string
        PartyID:
          type: string
        Status:
          type: string
        Amount:
          type: string
        Currency:
          type: string
        EffectiveDateTime:
          type: string
        ClearingDateTime:
          type: string
        PositionType:
          type: string
        PositionComponent:
          type: string
        AuthorisationReferenceID:
          type: string
        TransactionReferenceID:
          type: string
        ClearingMatchStatusCode:
          type: string
  securitySchemes:
    SecurityScheme:
      type: http
      description: Authentication
      scheme: basic
