---
openapi: 3.0.3
info:
  title: servicing-event-history
  version: 1.1.0-10
tags:
- name: Customer Servicing
paths:
  /ServicingEventHistory/V1/ServicingEvent/GetList/Request:
    post:
      tags:
      - Customer Servicing
      summary: "This method is used to retrieve a list of notes added onto the Customer,\
        \ Account or Card level, based on the given filter criteria"
      operationId: retrieve
      parameters:
      - name: fi-id
        in: header
        description: Financial Institution Identification
        required: true
        schema:
          maxLength: 37
          type: string
      - name: brand-id
        in: header
        description: Brand Identification
        schema:
          maxLength: 37
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ServicingRecordRetrievalRequest'
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ServicingRecordRetrievalResponse'
        "400":
          description: "Bad Request <br/><br/> <b>Error codes list:</b><br/><ul><li><em>HLXSNEHBR001\
            \ : PartyID required, please provide value.</em></li><li><em>HLXSNEHBR001\
            \ : PartyID must be a valid UUID of exactly 36 characters, please provide\
            \ a valid value.</em></li><li><em>HLXSNEHBR001 : Product exceeds maximum\
            \ 37 length allowed.</em></li><li><em>HLXSNEHBR001 : AgreementID must\
            \ be a valid UUID of exactly 36 characters, please provide a valid value.</em></li><li><em>HLXSNEHBR001\
            \ : PaymentInstrumentID must be a valid UUID of exactly 36 characters,\
            \ please provide a valid value.</em></li><li><em>HLXSNEHBR001 : Category\
            \ has to be either MNUL, AUTO or EXTR.</em></li><li><em>HLXSNEHBR001 :\
            \ Channel has to be either UINT, MBAP, INTR, EVNT or SYGN.</em></li><li><em>HLXSNEHBR001\
            \ : FromCreationDateTime must be valid and in YYYY-MM-DD'T'HH:MM:SS format.</em></li><li><em>HLXSNEHBR001\
            \ : FromCreationDateTime or ToCreationDateTime cannot be a future date\
            \ and time.</em></li><li><em>HLXSNEHBR001 : Invalid API request. The request\
            \ contains a ToCreationDateTime value, but the FromCreationDateTime value\
            \ is missing.</em></li><li><em>HLXSNEHBR001 : ToCreationDateTime must\
            \ be valid and in YYYY-MM-DD'T'HH:MM:SS format.</em></li><li><em>HLXSNEHBR001\
            \ : Invalid API request. The request contains a FromCreationDateTime value,\
            \ but the ToCreationDateTime value is missing.</em></li><li><em>HLXSNEHBR001\
            \ : ToCreationDateTime must be greater than FromCreationDateTime.</em></li><li><em>HLXSNEHBR001\
            \ : PageStartIndex has an invalid value. It must be an integer.</em></li><li><em>HLXSNEHBR001\
            \ : PageStartIndex cannot be less than 0. Please provide a valid value.</em></li><li><em>HLXSNEHBR001\
            \ : Invalid API request. The request contains a PageLimit value, but the\
            \ PageStartIndex value is missing.</em></li><li><em>HLXSNEHBR001 : PageLimit\
            \ has an invalid value. It must be an integer.</em></li><li><em>HLXSNEHBR001\
            \ : PageLimit cannot be less than 1. Please provide a valid value.</em></li><li><em>HLXSNEHBR001\
            \ : Invalid API request. The request contains a PageStartIndex value,\
            \ but the PageLimit value is missing.</em></li><li><em>HLXSNEHBR001 :\
            \ SortOrder has to be either ASCN or DESC.</em></li><li><em>HLXSNEHBR001\
            \ : Invalid API request. The request contains a SortField value, but the\
            \ SortOrder value is missing.</em></li><li><em>HLXSNEHBR001 : SortField\
            \ has to be either USID, USNM, CDTM or CHAN.</em></li><li><em>HLXSNEHBR001\
            \ : Invalid API request. The request contains a SortOrder value, but the\
            \ SortField value is missing.</em></li></ul>"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HelixErrorDetails'
        "401":
          description: Not Authorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HelixErrorDetails'
        "403":
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HelixErrorDetails'
        "404":
          description: "Not Found <br/><br/> <b>Error codes list:</b><br/><ul><li><em>HLXSNEHNF001\
            \ : There are no records present for the given criteria.</em></li></ul>"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HelixErrorDetails'
        "415":
          description: Unsupported Media Type
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HelixErrorDetails'
        "422":
          description: Unprocessable Entity
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HelixErrorDetails'
        "429":
          description: Too Many Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HelixErrorDetails'
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HelixErrorDetails'
        "502":
          description: Bad Gateway
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HelixErrorDetails'
        "503":
          description: Service Unavailable
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HelixErrorDetails'
        "504":
          description: Gateway Timeout
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HelixErrorDetails'
      x-proxy-name: Retrieve Notes
      x-group-name: Customer Servicing
  /ServicingEventHistory/V1/ServicingEvent/Initiate:
    post:
      tags:
      - Customer Servicing
      summary: "This API is used to add a new note onto the Customer, Account or Card\
        \ level."
      operationId: register
      parameters:
      - name: idempotency-id
        in: header
        description: Idempotency ID
        required: true
        schema:
          type: string
      - name: fi-id
        in: header
        description: Financial Institution Identification
        required: true
        schema:
          maxLength: 37
          type: string
      - name: brand-id
        in: header
        description: Brand Identification
        schema:
          maxLength: 37
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ServicingRecordCreationRequest'
      responses:
        "201":
          description: Created
        "400":
          description: "Bad Request <br/><br/> <b>Error codes list:</b><br/><ul><li><em>HLXSNEHBR001\
            \ : Description less than minimum 2 length allowed.</em></li><li><em>HLXSNEHBR001\
            \ : Description exceeds maximum 2000 length allowed.</em></li><li><em>HLXSNEHBR001\
            \ : PartyID required, please provide value.</em></li><li><em>HLXSNEHBR001\
            \ : PartyID must be a valid UUID of exactly 36 characters, please provide\
            \ a valid value.</em></li><li><em>HLXSNEHBR001 : Product exceeds maximum\
            \ 37 length allowed.</em></li><li><em>HLXSNEHBR001 : AgreementID must\
            \ be a valid UUID of exactly 36 characters, please provide a valid value.</em></li><li><em>HLXSNEHBR001\
            \ : PaymentInstrumentID must be a valid UUID of exactly 36 characters,\
            \ please provide a valid value.</em></li><li><em>HLXSNEHBR001 : UserID\
            \ less than minimum 2 length allowed.</em></li><li><em>HLXSNEHBR001 :\
            \ UserID exceeds maximum 320 length allowed.</em></li><li><em>HLXSNEHBR001\
            \ : UserName less than minimum 2 length allowed.</em></li><li><em>HLXSNEHBR001\
            \ : UserName exceeds maximum 320 length allowed.</em></li><li><em>HLXSNEHBR001\
            \ : Category has to be either MNUL, AUTO or EXTR.</em></li><li><em>HLXSNEHBR001\
            \ : Channel has to be either UINT, MBAP, INTR, EVNT or SYGN.</em></li></ul>"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HelixErrorDetails'
        "401":
          description: Not Authorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HelixErrorDetails'
        "403":
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HelixErrorDetails'
        "404":
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HelixErrorDetails'
        "415":
          description: Unsupported Media Type
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HelixErrorDetails'
        "422":
          description: Unprocessable Entity
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HelixErrorDetails'
        "429":
          description: Too Many Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HelixErrorDetails'
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HelixErrorDetails'
        "502":
          description: Bad Gateway
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HelixErrorDetails'
        "503":
          description: Service Unavailable
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HelixErrorDetails'
        "504":
          description: Gateway Timeout
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HelixErrorDetails'
        "200":
          description: OK
      x-proxy-name: Add a Note
      x-group-name: Customer Servicing
components:
  schemas:
    HelixErrorDetails:
      type: object
      properties:
        messages:
          type: array
          items:
            $ref: '#/components/schemas/HelixMessage'
    HelixMessage:
      type: object
      properties:
        errorCode:
          type: string
        type:
          type: string
        title:
          type: string
        detail:
          type: string
        instance:
          type: string
    ServicingRecordCreationRequest:
      required:
      - Description
      - PartyID
      type: object
      properties:
        Description:
          description: A note or servicing event description.
          type: string
        Product:
          description: Product to which the agreement belongs.
          type: string
        AgreementID:
          description: AgreementID to which the note or servicing event belongs (FEAID).
          type: string
        PaymentInstrumentID:
          description: PaymentInstrumentID to which the note or servicing event belongs
            (FEPID).
          type: string
        PartyID:
          description: PartyID to which the note or servicing event belongs (FECID).
          type: string
        UserID:
          description: The User ID of the Agent who creates the Servicing Event.
          type: string
        UserName:
          description: The User Name of the Agent who creates the Servicing Event.
          type: string
        Category:
          description: "Category of the Servicing Event. Valid values are: <UL><LI>\
            \ AUTO (Auto) - Automatically generated servicing event. </LI><LI> MNUL\
            \ (Manual) - Notes added manually. </LI><LI> EXTR (External) - Notes generated\
            \ by external systems. </LI> </UL>"
          type: string
        Channel:
          description: "Originating channel of the Servicing Event. Valid values are:\
            \ <UL><LI> UINT (Agent UI) </LI><LI> MBAP (Mobile App) </LI><LI> INTR\
            \ (External Interface) </LI> <LI> EVNT (Event) </LI> <LI> SYGN (System\
            \ Generated) </LI></UL>"
          type: string
    ServicingRecordRetrievalRequest:
      required:
      - PartyID
      type: object
      properties:
        Product:
          description: Product to which the Servicing Event belongs.
          type: string
        AgreementID:
          description: AgreementID to which the Servicing Event belongs (FEAID).
          type: string
        PaymentInstrumentID:
          description: PaymentInstrumentID to which the Servicing Event belongs (FEPID).
          type: string
        PartyID:
          description: PartyID to which the Servicing Event belongs (FECID). This
            is the required field while retrieving servicing events.
          type: string
        UserID:
          description: The User ID of the Agent who creates the Servicing Event.
          type: string
        UserName:
          description: The User Name of the Agent who creates the Servicing Event.
          type: string
        Category:
          description: "Category of the Servicing Event. Valid values are: <UL><LI>\
            \ AUTO (Auto) - Automatically generated servicing event. </LI><LI> MNUL\
            \ (Manual) - Notes added manually. </LI><LI> EXTR (External) - Notes generated\
            \ by external systems. </LI> </UL>"
          type: string
        Channel:
          description: "Originating channel of the Servicing Event. Valid values are:\
            \ <UL><LI> UINT (Agent UI) </LI><LI> MBAP (Mobile App) </LI><LI> INTR\
            \ (External Interface) </LI> <LI> EVNT (Event) </LI> <LI> SYGN (System\
            \ Generated) </LI></UL>"
          type: string
        Description:
          description: This field is used to perform a keyword search within the Description
            of a note or servicing event.
          type: string
        PageStartIndex:
          description: "The page start index is an optional field which specifies\
            \ the starting index for the page of results. It is an integer that represents\
            \ the index of the page. The first page corresponds to the PageStartIndex\
            \ value of 0. If PageStartIndex is provided in the request, PageLimit\
            \ must also be provided."
          type: string
        PageLimit:
          description: "The page limit is an optional parameter which specifies the\
            \ maximum number of records to return in the page of results. It is an\
            \ integer that represents the total number of records on a single page.\
            \ The PageLimit must have a minimum value of 1, indicating at least one\
            \ record per page. If PageLimit is provided in the request, PageStartIndex\
            \ must also be provided."
          type: string
        FromCreationDateTime:
          description: "This field is used to specify the starting point of the CreationDateTime\
            \ range for filtering. Only records with a CreationDateTime later than\
            \ or equal to this value will be included in the filtered results. If\
            \ FromCreationDateTime is provided in the request, ToCreationDateTime\
            \ must also be provided.<br/>ISO Format (YYYY-MM-DD'T'HH:MM:SS)."
          type: string
        ToCreationDateTime:
          description: "This field is used to specify the ending point of the CreationDateTime\
            \ range for filtering. Only records with a CreationDateTime earlier than\
            \ or equal to this value will be included in the filtered results. If\
            \ ToCreationDateTime is provided in the request, FromCreationDateTime\
            \ must also be provided.<br/>ISO Format (YYYY-MM-DD'T'HH:MM:SS)."
          type: string
        SortOrder:
          description: "Specifies the sorting order(Ascending or Descending) to perform\
            \ on requested SortField. If SortOrder is provided in the request, SortField\
            \ must also be provided. Valid values are: <UL><LI> ASCN (Ascending) </LI><LI>\
            \ DESC (Descending) </LI></UL>"
          type: string
        SortField:
          description: "Specifies the field based on which sorting is performed on\
            \ servicing event list. If SortOrder is provided in the request, SortField\
            \ must also be provided. Valid values are: <UL><LI> USID (UserId) </LI><LI>\
            \ USNM (UserName) </LI><LI> CDTM (CreationDateTime) </LI><LI> CHAN (Channel)\
            \ </LI></UL>"
          type: string
    ServicingRecordRetrievalResponse:
      type: object
      properties:
        Identification:
          description: A unique identifier assigned to each servicing event for identification
            and reference purposes.
          type: string
        FinancialInstitution:
          description: Financial Institution Identification.
          type: string
        Brand:
          description: Brand Identification.
          type: string
        Product:
          description: Product to which the Servicing Event belongs.
          type: string
        AgreementID:
          description: AgreementID to which the Servicing Event belongs (FEAID).
          type: string
        PaymentInstrumentID:
          description: PaymentInstrumentID to which the Servicing Event belongs (FEPID).
          type: string
        PartyID:
          description: PartyID to which the Servicing Event belongs (FECID).
          type: string
        UserID:
          description: The User ID of the Agent who creates the Servicing Event.
          type: string
        UserName:
          description: The User Name of the Agent who creates the Servicing Event.
          type: string
        Category:
          description: "Category of the Servicing Event. Valid values are: <UL><LI>\
            \ AUTO (Auto) - Automatically generated servicing event. </LI><LI> MNUL\
            \ (Manual) - Notes added manually. </LI><LI> EXTR (External) - Notes generated\
            \ by external systems. </LI> </UL>"
          type: string
        Channel:
          description: "Originating channel of the Servicing Event. Valid values are:\
            \ <UL><LI> UINT (Agent UI) </LI><LI> MBAP (Mobile App) </LI><LI> INTR\
            \ (External Interface) </LI> <LI> EVNT (Event) </LI> <LI> SYGN (System\
            \ Generated) </LI></UL>"
          type: string
        Description:
          description: Description of the servicing event.
          type: string
        CreationDateTime:
          description: Creation date and time of the servicing event.<br/>ISO Format
            (YYYY-MM-DD'T'HH:MM:SS).
          type: string
  securitySchemes:
    SecurityScheme:
      type: http
      description: Authentication
      scheme: basic
